=== Barteks-disipler/DAT107-O4/xml_stuff/lokallag.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:element name="lokallag" type="lokallagType"/>

    <xs:complexType name="lokallagType">
        <xs:sequence>
            <xs:element name="lag" type="lagType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="lagType">
        <xs:sequence>
            <xs:element name="info" type="infoType"/>
            <xs:element name="leder" type="lederType"/>
            <xs:element name="medlemmer" type="medlemmerType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="infoType">
        <xs:sequence>
            <xs:element name="navn" type="xs:string"/>
            <xs:element name="lokale" type="xs:string"/>
            <xs:element name="adresse" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="lederType">
        <xs:sequence>
            <xs:element name="navn" type="navnType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="medlemType">
        <xs:sequence>
            <xs:element name="navn" type="navnType"/>
            <xs:element name="kontakt" type="kontaktType"/>
            <xs:element name="adresse" type="adresseType"/>
            <xs:element name="status" type="xs:boolean"/>
            <xs:element name="avgifter" type="avgifterType"/>
        </xs:sequence>
        <xs:attribute name="mId" type="xs:positiveInteger" use="required"/>
    </xs:complexType>

    <xs:complexType name="navnType">
        <xs:sequence>
            <xs:element name="fornavn" type="xs:string"/>
            <xs:element name="etternavn" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="kontaktType">
        <xs:sequence>
            <xs:element name="telefon" type="xs:integer"/>
            <xs:element name="epost" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="adresseType">
        <xs:sequence>
            <xs:element name="gateadresse" type="xs:string"/>
            <xs:element name="postnummer">
                <xs:simpleType>
                    <xs:restriction base="xs:integer">
                        <xs:pattern value="[0-9]{4}"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="poststed" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="avgifterType">
        <xs:sequence>
            <xs:element name="avgift" type="avgiftType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="avgiftType">
        <xs:sequence>
            <xs:element name="aar">
                    <xs:simpleType>
                        <xs:restriction base="xs:integer">
                            <xs:pattern value="[1900-2100]{4}"/>
                        </xs:restriction>
                    </xs:simpleType>
            </xs:element>
            <xs:element name="betalt" type="xs:boolean"/>
            <xs:element name="dato" type="xs:dateTime"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="medlemmerType">
        <xs:sequence>
            <xs:element name="medlem" type="medlemType" minOccurs="1" maxOccurs="unbounded">
                <xs:unique name="mId">
                    <xs:selector xpath="medlem"/>
                    <xs:field xpath="@mId"/>
                </xs:unique>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Barteks-disipler/DAT107-O4/xml_stuff/lokallag.xml
<?xml version="1.0" encoding="UTF-8"?>
<lokallag xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="lokallag.xsd">
    <lag>
        <info>
            <navn></navn>
            <lokale></lokale>
            <adresse></adresse>
        </info>
        <leder>
            <navn>
                <fornavn></fornavn>
                <etternavn></etternavn>
            </navn>
        </leder>
        <medlemmer>
            <medlem mId="">
                <navn>
                    <fornavn></fornavn>
                    <etternavn></etternavn>
                </navn>
                <kontakt>
                    <telefon></telefon>
                    <epost></epost>
                </kontakt>
                <adresse>
                    <gateadresse></gateadresse>
                    <postnummer></postnummer>
                    <poststed></poststed>
                </adresse>
                <status></status>
                <avgifter>
                    <avgift>
                        <aar></aar>
                        <betalt></betalt>
                        <dato></dato>
                    </avgift>
                </avgifter>
            </medlem>
        </medlemmer>
    </lag>
</lokallag>
